# Generated by Django 3.1.3 on 2020-11-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='enddate',
            field=models.DateTimeField(help_text='DD/MM/YYYY'),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='startdate',
            field=models.DateTimeField(help_text='DD/MM/YYYY'),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
