# Generated by Django 3.1.3 on 2020-11-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201130_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organiser',
        ),
    ]
