# Generated by Django 3.1.3 on 2020-12-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201211_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='event',
            new_name='product',
        ),
    ]
